databases:
  - name: mybudget
  ipAllowList: []
   

services:
  - type: web
    name: rails
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mybudget
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  -type: redis
   name: redis
   ipAllowList: []
   plan: free
   maxmemoryPolicy: noeviction