databases:
  - name: Budget_production
    databaseName: Budget_production
    user: Budget_production

services:
  - type: web
    name: Budget_production
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Budget_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false