databases:
  - name: Budget_development
    ipAllowList: []
services:
  - type: web
    name: rails
    runtime: ruby
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Budget_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false